## Fase 1: Análisis Exploratorio de Datos (EDA)

In [1]:
import pandas as pd
import numpy as np

pd.set_option('display.max_columns', None)

1. Apertura del csv.

In [5]:
df_datos = pd.read_csv("human_cognitive_performance.csv")

df_datos.head(3)

User_ID  Age  Gender  Sleep_Duration  Stress_Level       Diet_Type  \
0      U1   57  Female             6.5             3  Non-Vegetarian   
1      U2   39  Female             7.6             9  Non-Vegetarian   
2      U3   26    Male             8.2             6      Vegetarian   

   Daily_Screen_Time Exercise_Frequency  Caffeine_Intake  Reaction_Time  \
0                6.5             Medium               41         583.33   
1               10.8               High              214         368.24   
2                5.7                Low              429         445.21   

   Memory_Test_Score  Cognitive_Score  AI_Predicted_Score  
0                 65            36.71               39.77  
1                 58            54.35               57.68  
2                 49            32.57               29.54

2. Ver las últimas filas.

In [10]:
df_datos.tail(3)

User_ID  Age  Gender  Sleep_Duration  Stress_Level       Diet_Type  \
79997  U79998   32  Female             7.3            10  Non-Vegetarian   
79998  U79999   34    Male             8.7             8      Vegetarian   
79999  U80000   41  Female             7.9             7      Vegetarian   

       Daily_Screen_Time Exercise_Frequency  Caffeine_Intake  Reaction_Time  \
79997                7.5                Low              462         249.57   
79998                7.2             Medium               96         319.48   
79999                2.0             Medium               27         263.21   

       Memory_Test_Score  Cognitive_Score  AI_Predicted_Score  
79997                 72            63.51               67.35  
79998                 82            81.43               77.95  
79999                 42            80.39               84.45

3. Ver el número total de filas y columnas.

In [16]:
df_datos.shape

(80000, 13)

4. Tener resumen del DATAFRAME, número de no valores no nulos, tipo de datos por columnas y número total de filas.

In [6]:
df_datos.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 80000 entries, 0 to 79999
Data columns (total 13 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   User_ID             80000 non-null  object 
 1   Age                 80000 non-null  int64  
 2   Gender              80000 non-null  object 
 3   Sleep_Duration      80000 non-null  float64
 4   Stress_Level        80000 non-null  int64  
 5   Diet_Type           80000 non-null  object 
 6   Daily_Screen_Time   80000 non-null  float64
 7   Exercise_Frequency  80000 non-null  object 
 8   Caffeine_Intake     80000 non-null  int64  
 9   Reaction_Time       80000 non-null  float64
 10  Memory_Test_Score   80000 non-null  int64  
 11  Cognitive_Score     80000 non-null  float64
 12  AI_Predicted_Score  80000 non-null  float64
dtypes: float64(5), int64(4), object(4)
memory usage: 7.9+ MB


5. Obtener estadísticas de los valores númericos del DataFrame y luego transponer el resultado.

In [7]:
df_datos.describe().T

count        mean         std    min     25%     50%  \
Age                 80000.0   38.525525   12.101876   18.0   28.00   39.00   
Sleep_Duration      80000.0    7.005332    1.734435    4.0    5.50    7.00   
Stress_Level        80000.0    5.493762    2.865308    1.0    3.00    5.00   
Daily_Screen_Time   80000.0    6.504646    3.167072    1.0    3.80    6.50   
Caffeine_Intake     80000.0  248.988213  144.541990    0.0  123.00  249.00   
Reaction_Time       80000.0  399.973579  115.369329  200.0  300.15  400.36   
Memory_Test_Score   80000.0   69.498350   17.305659   40.0   55.00   70.00   
Cognitive_Score     80000.0   58.172395   23.058522    0.0   40.91   58.36   
AI_Predicted_Score  80000.0   58.121357   23.119598    0.0   40.85   58.36   

                       75%     max  
Age                  49.00   59.00  
Sleep_Duration        8.50   10.00  
Stress_Level          8.00   10.00  
Daily_Screen_Time     9.20   12.00  
Caffeine_Intake     375.00  499.00  
Reaction_Time       499.25  599.99  
Memory_Test_Score    85.00   99.00  
Cognitive_Score      75.83  100.00  
AI_Predicted_Score   75.89  100.00

6. Obtener estadísticas de los valores categoricos del DataFrame y luego transponer el resultado.

In [8]:
df_datos.describe(include="O").T

count unique             top   freq
User_ID             80000  80000              U1      1
Gender              80000      3          Female  38404
Diet_Type           80000      3  Non-Vegetarian  47986
Exercise_Frequency  80000      3          Medium  31990

7. Revisar datos duplicados.

In [12]:

# Identificar los números duplicados
duplicados = df_datos[df_datos['User_ID'].duplicated()]
duplicados 

Empty DataFrame
Columns: [User_ID, Age, Gender, Sleep_Duration, Stress_Level, Diet_Type, Daily_Screen_Time, Exercise_Frequency, Caffeine_Intake, Reaction_Time, Memory_Test_Score, Cognitive_Score, AI_Predicted_Score]
Index: []

8. Ver las columnas del DataFrame.

In [13]:
df_datos.columns

Index(['User_ID', 'Age', 'Gender', 'Sleep_Duration', 'Stress_Level',
       'Diet_Type', 'Daily_Screen_Time', 'Exercise_Frequency',
       'Caffeine_Intake', 'Reaction_Time', 'Memory_Test_Score',
       'Cognitive_Score', 'AI_Predicted_Score'],
      dtype='object')

9. Ver valores únicos de la columna 'User_ID'.

In [14]:
df_datos['User_ID'].unique()

array(['U1', 'U2', 'U3', ..., 'U79998', 'U79999', 'U80000'], dtype=object)

10. Ver valores únicos de la columna 'Age'.

In [17]:
df_datos['Age'].unique()

array([57, 39, 26, 32, 50, 36, 48, 35, 29, 54, 18, 51, 24, 19, 21, 37, 20,
       33, 23, 22, 46, 44, 58, 43, 45, 49, 42, 47, 38, 27, 41, 31, 56, 30,
       55, 53, 34, 25, 59, 52, 28, 40], dtype=int64)

11. Ver valores únicos de la columna 'Gender'.

In [18]:
df_datos['Gender'].unique()

array(['Female', 'Male', 'Other'], dtype=object)

11. Ver valores únicos de la columna 'Sleep_Duration'.

In [19]:
df_datos['Sleep_Duration'].unique()

array([ 6.5,  7.6,  8.2,  7.8,  9.7,  7.4,  6.7,  6. ,  5.1,  7.9,  7.3,
        9.5,  9.3,  4.6,  6.3,  7.5,  5.7,  5.8,  8.7,  8.4,  4.1,  6.9,
        5.2,  9.4,  6.8,  4.8,  8.6,  6.6,  9.1,  8.1,  7.1,  8.3,  6.4,
        4.2,  9. ,  9.9,  4.7,  8.5,  8. ,  8.9,  4.5,  9.6,  5.6, 10. ,
        9.2,  5.9,  5.3,  8.8,  5. ,  5.5,  4.3,  7.2,  4.4,  4.9,  7.7,
        6.1,  9.8,  4. ,  5.4,  6.2,  7. ])

12. Ver valores únicos de la columna 'Stress_Level'.

In [20]:
df_datos['Stress_Level'].unique()

array([ 3,  9,  6,  2, 10,  1,  8,  5,  7,  4], dtype=int64)

13. Ver valores únicos de la columna 'Diet_Type'.

In [21]:
df_datos['Diet_Type'].unique()

array(['Non-Vegetarian', 'Vegetarian', 'Vegan'], dtype=object)

14. Ver valores únicos de la columna 'Daily_Screen_Time'.

In [22]:
df_datos['Daily_Screen_Time'].unique()

array([ 6.5, 10.8,  5.7,  8.3, 11.3,  6.6,  1.4,  6.8, 10.2,  9.1, 11.7,
        2.6,  5.5,  3.5,  6.1,  8.7,  3.1,  4.8,  5.6, 10.7,  4. ,  9.4,
       11. ,  7.5, 11.6,  4.9,  8.5,  2.2,  5. , 10.4,  1.3, 10.9, 10.3,
        5.2, 11.9,  3.7,  3.2,  4.1,  9.8,  5.1,  1.6,  5.8,  4.4,  4.6,
        7.2,  4.7,  7.1,  9.5,  1.7,  8.6, 10.6,  3.6,  4.2,  5.9,  4.5,
        3.4,  8. ,  1.8,  3. , 11.1,  9.2,  8.4,  9.7,  2.7,  2.4,  2.3,
        8.2,  5.3,  1.2,  2.8,  2.1,  7. , 10.1,  8.1,  9.9,  6.2,  8.8,
       11.5,  2.5,  7.4,  3.9,  4.3,  7.8, 10. ,  6.4,  1.9,  2.9,  6.3,
        1.1,  6.7,  3.3,  8.9,  3.8,  9.3,  6.9, 10.5,  5.4,  7.7,  1. ,
       11.4, 11.2, 12. ,  7.3,  2. , 11.8,  6. ,  9. ,  9.6,  1.5,  7.9,
        7.6])

15. Ver valores únicos de la columna 'Exercise_Frequency'.

In [23]:
df_datos['Exercise_Frequency'].unique()

array(['Medium', 'High', 'Low'], dtype=object)

16. Ver valores únicos de la columna 'Caffeine_Intake'.

In [36]:
df_datos['Caffeine_Intake'].unique()

array([ 41, 214, 429, 464, 365, 381,  39,   2, 244, 355,  50,  30, 342,
        67, 405, 158, 147, 207, 497, 281, 100, 283, 127, 178, 492,  54,
       218, 459, 332,   8, 156,  63, 305,  36,  86, 161, 413, 400, 414,
       279, 208,  85,  72, 262,  28, 162, 477,   5,  12, 170, 272, 143,
       185, 407, 172, 144,  22, 101, 241, 278, 491, 141, 291,  65, 230,
       319,  46, 246,  10,  84,  69,  90,  68, 211, 315, 116, 379, 420,
       243, 449, 486, 124, 317, 463, 399, 104, 448, 331, 176, 228, 323,
       372, 398, 362, 499, 220, 363, 135, 194, 146, 415, 498, 245, 293,
       282, 341, 456,  71, 259, 304, 377,  19, 140, 419,  34,  59, 274,
       114,  77,  89, 470, 257,  47, 376, 351, 356, 369, 109,   4, 343,
       494, 247, 145, 277, 154, 292, 151, 219, 391,   1, 481, 416, 349,
       139, 295, 120, 493, 157,  64,  32,  83,  33, 385, 198, 110, 256,
       433, 426, 314, 227, 269, 410, 231, 397,   7, 483,  18, 224, 301,
       344, 469,  61, 411, 203,  27, 472, 242, 302, 238, 201, 39

17. Contabilizar la frecuencia de valores únicos en la columna 'Caffeine_Intake'.

In [32]:
df_datos['Caffeine_Intake'].value_counts()

Caffeine_Intake
217    198
76     198
30     196
238    192
46     191
      ... 
264    134
112    134
173    133
373    132
246    132
Name: count, Length: 500, dtype: int64

18. Brindar estadistica de la columna 'Caffeine_Intake'.

In [30]:
df_datos['Caffeine_Intake'].agg(['min', 'max', 'mean']) #miligramos, diferentes bebidas con cafeina

min       0.000000
max     499.000000
mean    248.988213
Name: Caffeine_Intake, dtype: float64

19. Ver valores únicos de la columna 'Reaction_Time'.

In [ ]:
df_datos['Reaction_Time'].unique() #prueba cognitiva, tiempo de reacción a estimulos, se mide en milisegundos

array([583.33, 368.24, 445.21, ..., 205.88, 541.65, 290.17])

20. Contabilizar la frecuencia de valores únicos en la columna 'Reaction_Time'.

In [34]:
df_datos['Reaction_Time'].value_counts()

Reaction_Time
260.11    10
597.79     9
567.89     9
424.62     9
316.02     9
          ..
376.12     1
415.01     1
512.33     1
246.85     1
290.17     1
Name: count, Length: 34595, dtype: int64

21. Brindar estadistica de la columna 'Reaction_Time'.

In [35]:
df_datos['Reaction_Time'].agg(['min', 'max', 'mean'])

min     200.000000
max     599.990000
mean    399.973579
Name: Reaction_Time, dtype: float64

22. Ver valores únicos de la columna 'Memory_Test_Score'.

In [37]:
df_datos['Memory_Test_Score'].unique()

array([65, 58, 49, 94, 62, 70, 51, 60, 82, 54, 69, 84, 72, 74, 44, 93, 75,
       79, 47, 48, 68, 42, 99, 64, 95, 40, 73, 83, 98, 78, 46, 71, 89, 77,
       61, 88, 96, 86, 67, 56, 87, 81, 91, 80, 97, 52, 59, 45, 43, 76, 57,
       53, 85, 66, 92, 63, 50, 55, 41, 90], dtype=int64)

23. Brindar estadistica de la columna 'Memory_Test_Score'.

In [38]:
df_datos['Memory_Test_Score'].agg(['min', 'max', 'mean'])

min     40.00000
max     99.00000
mean    69.49835
Name: Memory_Test_Score, dtype: float64

24. Ver valores únicos de la columna 'Cognitive_Score'.

In [39]:
df_datos['Cognitive_Score'].unique()

array([36.71, 54.35, 32.57, ..., 13.29, 10.62, 17.77])

25. Brindar estadistica de la columna 'Cognitive_Score'.

In [40]:
df_datos['Cognitive_Score'].agg(['min', 'max', 'mean'])

min       0.000000
max     100.000000
mean     58.172395
Name: Cognitive_Score, dtype: float64

26. Ver valores únicos de la columna 'AI_Predicted_Score'.

In [41]:
df_datos['AI_Predicted_Score'].unique()

array([39.77, 57.68, 29.54, ...,  3.98,  8.2 , 15.7 ])

27. Brindar estadistica de la columna 'AI_Predicted_Score'.

In [42]:
df_datos['AI_Predicted_Score'].agg(['min', 'max', 'mean'])

min       0.000000
max     100.000000
mean     58.121357
Name: AI_Predicted_Score, dtype: float64